export const FETCH_PKMN_START = 'FETCH_PKMN_START';
export const FETCH_PKMN_SUCCESS = 'FETCH_PKMN_SUCCESS';
export const FETCH_PKMN_FAIL = 'FETCH_PKMN_FAILFETCH_PKMN_FAIL';
export const LOADING_POKEMONS = 'LOADING_POKEMONS';
export const CHANGE_GEN = 'CHANGE_GEN';

export const SET_CURRENT_PKMN = 'SET_CURRENT_PKMN';
export const FETCH_CURRENT_PKMN_START = 'FETCH_CURRENT_PKMN_START';
export const FETCH_CURRENT_PKMN_SUCCESS = 'FETCH_CURRENT_PKMN_SUCCESS';
export const FETCH_CURRENT_PKMN_FAIL = 'FETCH_CURRENT_PKMN_FAIL';
export const LOADING_CURRENT_PKMN = 'LOADING_CURRENT_PKMN';

export const FETCH_EVO_CHAIN = 'FETCH_EVO_CHAIN';
export const FETCH_EVO_CHAIN_START = 'FETCH_EVO_CHAIN_START';
export const FETCH_EVO_CHAIN_SUCCESS = 'FETCH_EVO_CHAIN_SUCCESS';
export const FETCH_EVO_CHAIN_FAIL = 'FETCH_EVO_CHAIN_FAIL';

export const ADD_TO_TEAM = 'ADD_TO_TEAM';
export const REMOVE_FROM_TEAM = 'REMOVE_FROM_TEAM';
export const CHANGE_TEAM_POSITION = "CHANGE_TEAM_POSITION";

export const EDIT_TEAM = "EDIT_TEAM"
export const SET_EDIT_PKMN = 'SET_EDIT_PKMN ';
export const FETCH_EDIT_PKMN_START = 'FETCH_EDIT_PKMN_START';
export const FETCH_EDIT_PKMN_SUCCESS = 'FETCH_EDIT_PKMN_SUCCESS';
export const FETCH_EDIT_PKMN_FAIL = 'FETCH_EDIT_PKMN_FAIL';
export const LOADING_EDIT_PKMN = 'LOADING_EDIT_PKMN';

export const FETCH_ITEMS_START = "FETCH_ITEMS_START";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAIL = "FETCH_ITEMS_FAIL";